### ISSUE TITLE
Conversion from Image to Mat

### ISSUE THREAD

**Issue by gbaranski** [rcastill/mat2image#4]
Hi, would it be possible to add conversions from Image to Mat?

**Comment by rcastill** [comment]
Seems like [cv-convert](https://docs.rs/cv-convert/latest/cv_convert/) has that conversion already implemented

**Comment by gbaranski** [comment]
maybe we could copy the implementation to your crate? or maybe the other way, your implementation to the cv-convert crate?

**Comment by rcastill** [comment]
[It is planned](https://github.com/jerry73204/rust-cv-convert/issues/10)

**Comment by gbaranski** [comment]
great. I think I can close this issue.
