### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by danielboros1990** [rcastill/mat2image#6]
Hi there,

do you have a plan maybe release a new version?

**Comment by rcastill** [comment]
Hi @danielboros1990,

What do you need updated?

I use this myself and it’s working fine for my use case.

If all you need is a dependency update, just submit a PR and I can merge.

**Comment by danielboros1990** [comment]
@rcastill I tried to use the released version and also the github version to convert opencv `Mat` to `DynamicImage` but always got compile error related to trait bounds for `MatTraitConstManual`, the solution was too use the `cv-convert` crate with updated deps.

**Comment by rcastill** [comment]
Yes, opencv made some breaking changes over time.

I'll be closing this. Feel free to comment, or open a new issue if needed.
